### ISSUE TITLE
class  CalculatorBaseVisitor seems to be missing

### ISSUE THREAD

**Issue by andy-abreu** [shmatov/antlr4-calculator#2]
Hello I'm new to antlr 4 and I wanted to use your calculator as an example to get started. After following your steps to get this calculator going, it seems like the compiler can't find CalculatorBaseVisitor which CalculatorBaseVisitorImpl extends. Was this supposed to be generated or is it supposed to be part of the source code? If it's supposed to be part of the source code, it's not checked in.

**Comment by shmatov** [comment]
Hey!
`CalculatorBaseVisitor` should be generated by ANTLR. Make sure that you run `antlr4` with `-visitor` option. At least, all this stuff works with ANTLR version 4.5.3.
